site_name: Supportify
plugins:
- search
- swagger-ui-tag
nav:
  - Home: index.md
  - API Reference: api-reference.md
extra_javascript:
  - js/swagger-ui-bundle.js
  - js/swagger-ui-standalone-preset.js
extra_css:
  - css/swagger-ui.css
